//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFlex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imf_traducciones_trad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public imf_traducciones_trad()
        {
            this.imf_productos_prod = new HashSet<imf_productos_prod>();
        }
    
        public int tradIdTraduccion { get; set; }
        public string tradTraduccion { get; set; }
        public Nullable<int> tradIdUsuarioRegistro { get; set; }
        public Nullable<System.DateTime> tradFechaRegistro { get; set; }
        public Nullable<int> tradIdUsuarioUltimaModificacion { get; set; }
        public Nullable<System.DateTime> tradFechaUltimaModificacion { get; set; }
    
        public virtual imf_usuarios_usr UsuarioRegistro { get; set; }
        public virtual imf_usuarios_usr UsuarioUltimaModificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_productos_prod> imf_productos_prod { get; set; }
    }
}
