//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFlex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imf_productos_prod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public imf_productos_prod()
        {
            this.imf_facturadetalle_fde = new HashSet<imf_facturadetalle_fde>();
        }
    
        public int prodIdProducto { get; set; }
        public string prodDescripcionRSI { get; set; }
        public string prodTraduccion { get; set; }
        public string prodNumeroParte { get; set; }
        public Nullable<bool> prodStatus { get; set; }
        public string prodMarca { get; set; }
        public string prodModelo { get; set; }
        public string prodSubModelo { get; set; }
        public Nullable<int> prodIdPaisOrigen { get; set; }
        public string prodFraccionArancelaria { get; set; }
    
        public virtual imf_paises_pai imf_paises_pai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_facturadetalle_fde> imf_facturadetalle_fde { get; set; }
    }
}
