//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFlex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imf_usuarios_usr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public imf_usuarios_usr()
        {
            this.imf_facturadetalle_fde = new HashSet<imf_facturadetalle_fde>();
            this.imf_facturas_fac = new HashSet<imf_facturas_fac>();
            this.imf_importaciones_imp_exporto = new HashSet<imf_importaciones_imp>();
            this.imf_importaciones_imp_finalizo = new HashSet<imf_importaciones_imp>();
            this.imf_importaciones_imp_registro = new HashSet<imf_importaciones_imp>();
            this.imf_importaciones_imp = new HashSet<imf_importaciones_imp>();
            this.TradRegistro = new HashSet<imf_traducciones_trad>();
            this.TradUltimaModificacion = new HashSet<imf_traducciones_trad>();
        }
    
        public int usrIdUsuario { get; set; }
        public string usrUserName { get; set; }
        public string usrPassword { get; set; }
        public string userNombre { get; set; }
        public string usrApellidoPaterno { get; set; }
        public string usrApellidoMaterno { get; set; }
        public string usrEmail { get; set; }
        public Nullable<System.DateTime> usrFechaRegistro { get; set; }
        public Nullable<int> usrIdRol { get; set; }
    
        public virtual imf_roles_rls imf_roles_rls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_facturadetalle_fde> imf_facturadetalle_fde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_facturas_fac> imf_facturas_fac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_importaciones_imp> imf_importaciones_imp_exporto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_importaciones_imp> imf_importaciones_imp_finalizo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_importaciones_imp> imf_importaciones_imp_registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_importaciones_imp> imf_importaciones_imp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_traducciones_trad> TradRegistro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imf_traducciones_trad> TradUltimaModificacion { get; set; }
    }
}
